apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kcda-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
           name: kcda
           port: 
            number: 80
